import assert from "node:assert/strict";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, it } from "node:test";

import {
  createNeonNodePairingRequest,
  createNeonNodePairingSnapshot,
  createNeonNodePairingTokenGateSnapshot,
  recordNeonNodePairingApproval,
  renderNeonNodePairingTokenGateReport,
  type INeonCutoverGate,
  type INeonCutoverGateSnapshot
} from "../src/index.js";

describe("Neonika Node Pairing Token Gate", () => {
  it("keeps approved shadow pairings locked before canary cutover", async () => {
    const projectRoot = await createTempProjectRoot();

    try {
      const request = await createApprovedRequest(projectRoot);
      const snapshot = await createNeonNodePairingTokenGateSnapshot(projectRoot, {
        now: () => new Date("2026-06-01T00:02:00.000Z")
      });

      assert.equal(snapshot.state, "locked");
      assert.equal(snapshot.totals.eligibleApprovals, 1);
      assert.equal(snapshot.eligibleApprovals[0]?.requestId, request.requestId);
      assert.equal(snapshot.eligibleApprovals[0]?.tokenIssued, false);
      assert.equal(snapshot.blockers.some((blocker) => blocker.id === "cutover-stage-before-canary"), true);
      assert.equal(snapshot.blockers.some((blocker) => blocker.id === "cutover-gate-not-ready"), true);
      assert.deepEqual(
        snapshot.invariants,
        [
          "No device token material is generated by this gate.",
          "Pairing approvals must stay tokenIssued=false until the canary token issuer exists.",
          "Raw public keys are never persisted in Neonika state."
        ]
      );
    } finally {
      await rm(projectRoot, { force: true, recursive: true });
    }
  });

  it("reports ready-for-canary only when an approved shadow request and passing canary gate exist", async () => {
    const projectRoot = await createTempProjectRoot();

    try {
      await createApprovedRequest(projectRoot);
      const pairingSnapshot = await createNeonNodePairingSnapshot(projectRoot, {
        now: () => new Date("2026-06-01T00:02:00.000Z")
      });
      const snapshot = await createNeonNodePairingTokenGateSnapshot(projectRoot, {
        cutoverSnapshot: createCanaryCutoverSnapshot(),
        pairingSnapshot,
        now: () => new Date("2026-06-01T00:03:00.000Z")
      });

      assert.equal(snapshot.state, "ready-for-canary");
      assert.equal(snapshot.cutoverStage, "canary");
      assert.equal(snapshot.currentGateState, "pass");
      assert.equal(snapshot.blockers.length, 0);
      assert.equal(snapshot.totals.approvedShadow, 1);
      assert.equal(snapshot.eligibleApprovals[0]?.deviceId, "operator-phone");
      assert.equal(snapshot.eligibleApprovals[0]?.tokenIssued, false);
    } finally {
      await rm(projectRoot, { force: true, recursive: true });
    }
  });

  it("renders blockers and eligible approvals for operators", async () => {
    const projectRoot = await createTempProjectRoot();

    try {
      await createApprovedRequest(projectRoot);
      const report = renderNeonNodePairingTokenGateReport(
        await createNeonNodePairingTokenGateSnapshot(projectRoot, {
          now: () => new Date("2026-06-01T00:02:00.000Z")
        })
      );

      assert.match(report, /Neonika Node Pairing Token Gate: locked/);
      assert.match(report, /cutover-stage-before-canary/);
      assert.match(report, /tokenIssued=false/);
      assert.match(report, /No device token material is generated/);
    } finally {
      await rm(projectRoot, { force: true, recursive: true });
    }
  });
});

async function createApprovedRequest(projectRoot: string): Promise<{ readonly requestId: string }> {
  const request = await createNeonNodePairingRequest(
    projectRoot,
    {
      requestId: "pair-token-gate-request",
      deviceId: "operator-phone",
      publicKey: "raw-public-key",
      displayName: "Operator Phone",
      platform: "ios",
      requestedRole: "operator",
      requestedScopes: ["operator.pairing"]
    },
    {
      now: () => new Date("2026-06-01T00:00:00.000Z")
    }
  );

  await recordNeonNodePairingApproval(
    projectRoot,
    {
      requestId: request.requestId,
      decision: "approve",
      decidedBy: "chaty",
      reason: "operator reviewed"
    },
    {
      now: () => new Date("2026-06-01T00:01:00.000Z")
    }
  );

  return {
    requestId: request.requestId
  };
}

function createCanaryCutoverSnapshot(): INeonCutoverGateSnapshot {
  const gates: readonly INeonCutoverGate[] = [
    createGate("shadow", "Shadow", "pass"),
    createGate("mirror", "Mirror", "pass"),
    createGate("canary", "Canary", "pass"),
    createGate("primary", "Primary", "locked"),
    createGate("retire", "Retire", "locked")
  ];

  return {
    state: "ready",
    generatedAt: "2026-06-01T00:03:00.000Z",
    currentStage: "canary",
    nextStage: "primary",
    gates,
    source: {
      projectRoot: "/tmp/neonika-token-gate",
      doctorState: "pass",
      routeState: "ready",
      mirrorEvidenceState: "ready",
      mirrorAcceptedCount: 2,
      gatewayRuns: 5,
      latestRunId: "run-token-gate",
      rollbackConfigured: true
    }
  };
}

function createGate(id: INeonCutoverGate["id"], label: string, state: INeonCutoverGate["state"]): INeonCutoverGate {
  return {
    id,
    label,
    state,
    summary: `${label} gate ${state}`,
    requiredEvidence: ["operator evidence"],
    evidence: ["evidence present"],
    recovery: state === "pass" ? [] : ["keep previous stage active"],
    rollback: "Keep current route unchanged."
  };
}

async function createTempProjectRoot(): Promise<string> {
  return await mkdtemp(join(tmpdir(), "neonika-node-token-gate-"));
}
