import { type TCutoverStageId } from "../core/cutover.js";
import {
  createNeonCutoverGateSnapshot,
  type INeonCutoverGateSnapshot,
  type TNeonCutoverGateState,
  type TNeonCutoverReadinessState
} from "../core/cutoverGate.js";
import {
  createNeonNodePairingSnapshot,
  type INeonNodePairingApprovalRecord,
  type INeonNodePairingRequestSummary,
  type INeonNodePairingSnapshot
} from "./neonNodePairing.js";

export type TNeonNodePairingTokenGateState = "locked" | "ready-for-canary";

export type TNeonNodePairingTokenGateBlockerId =
  | "approval-request-missing"
  | "cutover-gate-not-ready"
  | "cutover-stage-before-canary"
  | "no-approved-shadow-approval";

export interface ICreateNeonNodePairingTokenGateSnapshotOptions {
  readonly now?: () => Date;
  readonly pairingSnapshot?: INeonNodePairingSnapshot;
  readonly cutoverSnapshot?: INeonCutoverGateSnapshot;
}

export interface INeonNodePairingTokenGateBlocker {
  readonly id: TNeonNodePairingTokenGateBlockerId;
  readonly summary: string;
  readonly recovery: string;
}

export interface INeonNodePairingTokenGateApproval {
  readonly approvalId: string;
  readonly requestId: string;
  readonly deviceId: string;
  readonly displayName?: string;
  readonly requestedRole: string;
  readonly requestedScopes: readonly string[];
  readonly decidedBy: string;
  readonly decidedAt: string;
  readonly tokenIssued: false;
}

export interface INeonNodePairingTokenGateTotals {
  readonly approvals: number;
  readonly approvedShadow: number;
  readonly eligibleApprovals: number;
  readonly blockers: number;
}

export interface INeonNodePairingTokenGateSource {
  readonly projectRoot: string;
  readonly pairingRequestPath: string;
  readonly pairingApprovalPath: string;
  readonly cutoverStage: TCutoverStageId;
  readonly cutoverState: TNeonCutoverReadinessState;
  readonly currentGateState: TNeonCutoverGateState | "missing";
}

export interface INeonNodePairingTokenGateSnapshot {
  readonly state: TNeonNodePairingTokenGateState;
  readonly generatedAt: string;
  readonly cutoverStage: TCutoverStageId;
  readonly cutoverState: TNeonCutoverReadinessState;
  readonly currentGateState: TNeonCutoverGateState | "missing";
  readonly eligibleApprovals: readonly INeonNodePairingTokenGateApproval[];
  readonly blockers: readonly INeonNodePairingTokenGateBlocker[];
  readonly invariants: readonly string[];
  readonly totals: INeonNodePairingTokenGateTotals;
  readonly source: INeonNodePairingTokenGateSource;
}

const canaryTokenStages: readonly TCutoverStageId[] = ["canary", "primary", "retire"];

const tokenGateInvariants = [
  "No device token material is generated by this gate.",
  "Pairing approvals must stay tokenIssued=false until the canary token issuer exists.",
  "Raw public keys are never persisted in Neonika state."
] as const;

export async function createNeonNodePairingTokenGateSnapshot(
  projectRoot: string,
  options: ICreateNeonNodePairingTokenGateSnapshotOptions = {}
): Promise<INeonNodePairingTokenGateSnapshot> {
  const now = options.now ?? (() => new Date());
  const [pairingSnapshot, cutoverSnapshot] = await Promise.all([
    options.pairingSnapshot ?? createNeonNodePairingSnapshot(projectRoot, options.now ? { now } : {}),
    options.cutoverSnapshot ?? createNeonCutoverGateSnapshot(projectRoot, options.now ? { now } : {})
  ]);
  const currentGate = cutoverSnapshot.gates.find((gate) => gate.id === cutoverSnapshot.currentStage);
  const approvedShadowApprovals = pairingSnapshot.approvals.filter(
    (approval) => approval.stateAfterDecision === "approved-shadow" && approval.tokenIssued === false
  );
  const { eligibleApprovals, missingRequestApprovals } = createEligibleApprovals(
    pairingSnapshot.requests,
    approvedShadowApprovals
  );
  const blockers = createTokenGateBlockers({
    approvedShadowApprovals,
    cutoverSnapshot,
    currentGateState: currentGate?.state ?? "missing",
    missingRequestApprovals
  });

  return {
    state: blockers.length === 0 ? "ready-for-canary" : "locked",
    generatedAt: now().toISOString(),
    cutoverStage: cutoverSnapshot.currentStage,
    cutoverState: cutoverSnapshot.state,
    currentGateState: currentGate?.state ?? "missing",
    eligibleApprovals,
    blockers,
    invariants: tokenGateInvariants,
    totals: {
      approvals: pairingSnapshot.totals.approvals,
      approvedShadow: pairingSnapshot.totals.approvedShadow,
      eligibleApprovals: eligibleApprovals.length,
      blockers: blockers.length
    },
    source: {
      projectRoot,
      pairingRequestPath: pairingSnapshot.source.requestPath,
      pairingApprovalPath: pairingSnapshot.source.approvalPath,
      cutoverStage: cutoverSnapshot.currentStage,
      cutoverState: cutoverSnapshot.state,
      currentGateState: currentGate?.state ?? "missing"
    }
  };
}

export function renderNeonNodePairingTokenGateReport(
  snapshot: INeonNodePairingTokenGateSnapshot
): string {
  const blockerLines =
    snapshot.blockers.length > 0
      ? snapshot.blockers.map((blocker) => `- ${blocker.id}: ${blocker.summary}`)
      : ["- none"];
  const approvalLines =
    snapshot.eligibleApprovals.length > 0
      ? snapshot.eligibleApprovals.map(
          (approval) =>
            `- ${approval.approvalId}: ${approval.deviceId} / ${approval.requestedRole} / tokenIssued=${approval.tokenIssued}`
        )
      : ["- none"];

  return [
    `Neonika Node Pairing Token Gate: ${snapshot.state}`,
    `Cutover: ${snapshot.cutoverStage} / ${snapshot.cutoverState} / gate=${snapshot.currentGateState}`,
    `Totals: eligible=${snapshot.totals.eligibleApprovals} blockers=${snapshot.totals.blockers}`,
    "Blockers:",
    ...blockerLines,
    "Eligible approvals:",
    ...approvalLines,
    "Invariants:",
    ...snapshot.invariants.map((invariant) => `- ${invariant}`)
  ].join("\n");
}

function createEligibleApprovals(
  requests: readonly INeonNodePairingRequestSummary[],
  approvals: readonly INeonNodePairingApprovalRecord[]
): {
  readonly eligibleApprovals: readonly INeonNodePairingTokenGateApproval[];
  readonly missingRequestApprovals: readonly INeonNodePairingApprovalRecord[];
} {
  const requestById = new Map(requests.map((request) => [request.requestId, request]));
  const eligibleApprovals: INeonNodePairingTokenGateApproval[] = [];
  const missingRequestApprovals: INeonNodePairingApprovalRecord[] = [];

  for (const approval of approvals) {
    const request = requestById.get(approval.requestId);

    if (!request) {
      missingRequestApprovals.push(approval);
      continue;
    }

    eligibleApprovals.push({
      approvalId: approval.approvalId,
      requestId: approval.requestId,
      deviceId: request.deviceId,
      ...(request.displayName ? { displayName: request.displayName } : {}),
      requestedRole: request.requestedRole,
      requestedScopes: request.requestedScopes,
      decidedBy: approval.decidedBy,
      decidedAt: approval.decidedAt,
      tokenIssued: approval.tokenIssued
    });
  }

  return {
    eligibleApprovals,
    missingRequestApprovals
  };
}

function createTokenGateBlockers(input: {
  readonly approvedShadowApprovals: readonly INeonNodePairingApprovalRecord[];
  readonly cutoverSnapshot: INeonCutoverGateSnapshot;
  readonly currentGateState: TNeonCutoverGateState | "missing";
  readonly missingRequestApprovals: readonly INeonNodePairingApprovalRecord[];
}): readonly INeonNodePairingTokenGateBlocker[] {
  const blockers: INeonNodePairingTokenGateBlocker[] = [];

  if (input.approvedShadowApprovals.length === 0) {
    blockers.push({
      id: "no-approved-shadow-approval",
      summary: "No approved shadow pairing audit exists.",
      recovery: "Approve one pending pairing request in shadow mode first."
    });
  }

  if (input.missingRequestApprovals.length > 0) {
    blockers.push({
      id: "approval-request-missing",
      summary: `${input.missingRequestApprovals.length} approval record(s) no longer match a pairing request.`,
      recovery: "Keep request and approval audit files together before issuing device tokens."
    });
  }

  if (!canaryTokenStages.includes(input.cutoverSnapshot.currentStage)) {
    blockers.push({
      id: "cutover-stage-before-canary",
      summary: `Current cutover stage is ${input.cutoverSnapshot.currentStage}, not canary or later.`,
      recovery: "Keep node token issuing disabled until mirror evidence unlocks canary."
    });
  }

  if (input.cutoverSnapshot.state !== "ready" || input.currentGateState !== "pass") {
    blockers.push({
      id: "cutover-gate-not-ready",
      summary: `Cutover gate is ${input.cutoverSnapshot.state} with current gate ${input.currentGateState}.`,
      recovery: "Run Doctor, mirror evidence, rollback config, and canary approval gates until the current gate passes."
    });
  }

  return blockers;
}
